### ISSUE TITLE
infinite loading when api is down

### ISSUE THREAD

**Issue by esion** [ziir/caliopen.web#3]
Nice job !   
Very easy to install & start.

It's not very important, but probably easy to do : The server should render an error 500 when api is not available.

**Comment by ziir** [comment]
Thanks for the feedback, I'll look into it asap :)

**Comment by ziir** [comment]
It was very important :)
Any error on the HTTP call to Auth API now correctly propagates to error middleware, thus rendering an error page.

So much left to do anyway :)

If you'd like to work on this, please don't hesitate to issue or PR or both :)

Thanks again
